name: working dir and shells
on: [push]
defaults:
    run:
        shell: bash # Runs all jobs in workflow in bash
jobs:
    display-working-dir-location:
        runs-on: ubuntu-latest
        steps:
            - name: display working dir and list files
              run: |
                pwd
                ls -a
                echo "GITHUB_SHA"
                echo "GITHUB_REPOSITORY"
                echo "echo $GITHUB_WORKSPACE"
            - name: Change working directory
              working-directory: /home/runner
              run: pwd