name: first workflow
on: [push] # A trigger that tells GitHub Actions to run a workflow whenever code is pushed to the repository.

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "hello world"
            - name: multiline commands
              run: |
                node -v
                npm -v
    
    parallel-job-macos:
        runs-on: macos-latest
        steps:
            - name: show mac version
              run: sw_vers

    dependent-job:
        runs-on: windows-latest
        needs: run-shell-commands # This job is run only after run-shell-commands is executed
        steps:
            - name: echo a string 
              run: Write-Output " Windows String"
            - name: Error 
              run: doesnotexits